# Generated by Django 2.2.6 on 2019-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
