# Generated by Django 2.2.6 on 2019-12-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeregistrationmodel',
            name='contact_number',
            field=models.IntegerField(unique=True),
        ),
    ]
