# Generated by Django 2.2.6 on 2019-12-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0002_auto_20191228_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeregistrationmodel',
            name='status',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
