# Generated by Django 2.2.6 on 2019-12-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0003_policeregistrationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeregistrationmodel',
            name='complete_address',
            field=models.TextField(default=True),
        ),
    ]
