# Generated by Django 2.2.6 on 2019-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0004_policeregistrationmodel_complete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeregistrationmodel',
            name='contact_number',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
