# Generated by Django 2.2.6 on 2019-12-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0005_auto_20191228_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeregistrationmodel',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
