# Generated by Django 2.2.6 on 2019-12-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_police', '0007_auto_20191228_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeregistrationmodel',
            name='contact_number',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
