# Generated by Django 2.2.6 on 2019-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_NGOs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLettersModel',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_file', models.FileField(upload_to='files/')),
                ('sender_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('sender_mail', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('data_of_posting', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
