# Generated by Django 2.2.6 on 2019-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='complaint_letter',
            new_name='complaint_details',
        ),
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='complaint_given_by',
            new_name='complaint_sender_name',
        ),
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='contact_number',
            new_name='complaint_sender_number',
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='from_address',
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='complaint_sender_place',
            field=models.CharField(default=True, max_length=70),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='complainting_place',
            field=models.CharField(default=True, max_length=70),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='date_of_giving',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
